version: '3.8'

services:
  app:
    container_name: bun-htmx-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public  # Mount static assets
      - ./meals.json:/app/meals.json  # Mount JSON file for updates
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: meal-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
